{{- if .Values.gotenberg.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "paperless-ngx.fullname" . }}-gotenberg
  labels:
    {{- include "paperless-ngx.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "paperless-ngx.name" . }}-gotenberg
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "paperless-ngx.name" . }}-gotenberg
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: gotenberg
          image: "{{ .Values.gotenberg.image.repository }}:{{ .Values.gotenberg.image.tag }}"
          imagePullPolicy: {{ .Values.gotenberg.image.pullPolicy }}
          args:
            {{- toYaml .Values.gotenberg.args | nindent 12 }}
          ports:
            - containerPort: {{ .Values.gotenberg.service.port }}
              name: http-gotenberg
          {{- with .Values.gotenberg.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
{{- end }}
