apiVersion: v1
kind: Service
metadata:
  name: {{ include "paperless-ngx.fullname" . }}
  labels:
    {{- include "paperless-ngx.labels" . | nindent 4 }}
spec:
  type: {{ .Values.paperless.service.type }}
  ports:
    - port: {{ .Values.paperless.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "paperless-ngx.selectorLabels" . | nindent 4 }}
