{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "paperless-ngx.fullname" . }}-postgresql
  labels:
    {{- include "paperless-ngx.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.postgresql.service.port }}
      targetPort: tcp-postgresql
      protocol: TCP
      name: tcp-postgresql
  selector:
    app.kubernetes.io/name: {{ include "paperless-ngx.name" . }}-postgresql
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
